apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
# O scrape_interval define de quanto em quanto tempo o Prometheus coleta métricas.
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets:
              - "localhost:9090"

      - job_name: "kubernetes-cadvisor"
        scheme: https
        kubernetes_sd_configs:
          - role: node

        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true

        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)

          - target_label: __address__
            replacement: kubernetes.default.svc:443

          - source_labels:
              - __meta_kubernetes_node_name
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor

      - job_name: "kube-state-metrics"
        static_configs:
          - targets:
              # Mudamos de 'monitoring' para 'kube-system' e a porta para 8080
              - "kube-state-metrics.kube-system.svc.cluster.local:8080"
      # --- CONFIGURAÇÃO PARA A API .NET ---
      - job_name: "dotnet-api"
        metrics_path: '/metrics' # Caminho padrão onde o .NET costuma expor as métricas
        static_configs:
          - targets:
              # ATENÇÃO: Substitua os valores abaixo pelo Service real da sua API.
              # Formato: "cadastro-api.nome-do-namespace.svc.cluster.local:porta"
              - "cadastro-api.api.svc.cluster.local:80"