apiVersion: v1
kind: Service
metadata:
  name: cadastro-api
  namespace: api

spec:
  type: NodePort
  selector:
    app: cadastro-api

  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008