---
apiVersion: v1
kind: Namespace
metadata:
  name: zabbix-lab
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: zabbix-lab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-mysql
  namespace: zabbix-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-mysql
  template:
    metadata:
      labels:
        app: zabbix-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        args: 
        - "--default-authentication-plugin=mysql_native_password"
        - "--log-bin-trust-function-creators=1"        
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "senha_root_super_secreta"
        - name: MYSQL_USER
          value: "zabbix"
        - name: MYSQL_PASSWORD
          value: "senha_forte_zabbix"
        - name: MYSQL_DATABASE
          value: "zabbix"
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql  # Aqui é onde o MySQL guarda os dados físicos
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: zabbix-lab
spec:
  selector:
    app: zabbix-mysql
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  namespace: zabbix-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
      - name: zabbix-server
        image: zabbix/zabbix-server-mysql:latest
        ports:
        - containerPort: 10051
        env:
        - name: DB_SERVER_HOST
          value: "mysql-svc"
        - name: MYSQL_USER
          value: "zabbix"
        - name: MYSQL_PASSWORD
          value: "senha_forte_zabbix"
        - name: MYSQL_DATABASE
          value: "zabbix"
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-server-svc
  namespace: zabbix-lab
spec:
  selector:
    app: zabbix-server
  ports:
    - port: 10051
      targetPort: 10051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web
  namespace: zabbix-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-web
  template:
    metadata:
      labels:
        app: zabbix-web
    spec:
      containers:
      - name: zabbix-web
        image: zabbix/zabbix-web-nginx-mysql:latest
        ports:
        - containerPort: 8080
        env:
        - name: ZBX_SERVER_HOST
          value: "zabbix-server-svc"
        - name: DB_SERVER_HOST
          value: "mysql-svc"
        - name: MYSQL_USER
          value: "zabbix"
        - name: MYSQL_PASSWORD
          value: "senha_forte_zabbix"
        - name: MYSQL_DATABASE
          value: "zabbix"
        - name: PHP_TZ
          value: "America/Sao_Paulo"